//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shtrih
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id_prod { get; set; }
        public string Name { get; set; }
        public Nullable<long> Shtrih_number { get; set; }
    }
}
